### PR TITLE
Calendar

### PR DESCRIPTION
**Pull request by SamGuay**
I'm getting this error when I generate the .ics feed on my computer. Hopefully, the problem is with my computer, and not the code :upside_down_face: . Pushing it to test.. 

```
Errors:
    Lines not delimited by CRLF sequence near line # 1Reference: RFC 5545 3.1. Content Lines
```

Documentation related to this [error here](https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html)

### CODE REVIEW

**Comment by pbellec** [comment]
This looks amazing! 

Couple of suggestions: 
 * remove the changes in REGISTER and the top bar, this has already been done.
 * move the week-by-week description of content into a new tab called WEEKS.
 * keep the new schedule under SCHEDULE

**Comment by SamGuay** [comment]
Alright, here's what I did: 

> Couple of suggestions:
>    - [x]  remove the changes in REGISTER and the top bar, this has already been done.

Reverted the change in English, made the change for the FR version.

>    - [x]   move the week-by-week description of content into a new tab called WEEKS.

Weeks and Semaines tabs were created.

>    - [x]  keep the new schedule under SCHEDULE

Schedule and Horaire will display the current schedule found in `/data/en/schedule.yaml`.
Sorry not sorry for the Frenchies, the schedule will be displayed only in English. 

PS: For the recordings, we might want to create a new column.

**Comment by pbellec** [comment]
This is awesome!! Huge thanks @SamGuay 

Also I love that the schedule will be easy to maintain. This is where the switch to hugo is really paying off.

**Comment by SamGuay** [comment]
I tried to make it as easy to maintain as possible, hence the single schedule.yaml data file. It could have been done totally differently. But the way I did it, people won't have to bother finding the right files for their week, etc.

**Pull request merged**
