### PR TITLE
Project Report (fMRI-sex-classification) - Tajwar Sultana

### PR DESCRIPTION
**Pull request by tjays7**
Please review the project report. If any changes required, please let me know.

### CODE REVIEW

**Comment by SamGuay** [comment]
Nice use of GIFs :)

**Comment by tjays7** [comment]
> There are conflicts because you deleted the files inside the `project/template/` dir. Can you revert these changes? Once you push your changes on GH, it will automatically commit it to the pull request as well.
> 
> Thanks

I reverted those changes and then changed template directory name to "fMRI-sex-classification" using copy command. Following is the git status:


> Changes not staged for commit:
>   (use "git add/rm <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
>         deleted:    content/en/project/template/bhs2020.png
>         deleted:    content/en/project/template/dontpanic.jpg
>         deleted:    content/en/project/template/enter.jpg
>         deleted:    content/en/project/template/index.md
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>         content/en/project/fMRI-sex-classification/bhs2020.png
>         content/en/project/fMRI-sex-classification/dontpanic.jpg
>         content/en/project/fMRI-sex-classification/enter.jpg

Renaming considered as deleting. To commit these changes, I will have to use "git rm" which will again cause conflict.

**Comment by tjays7** [comment]
> > There are conflicts because you deleted the files inside the `project/template/` dir. Can you revert these changes? Once you push your changes on GH, it will automatically commit it to the pull request as well.
> > Thanks
> 
> I reverted those changes and then changed template directory name to "fMRI-sex-classification" using copy command. Following is the git status:
> 
> > Changes not staged for commit:
> > (use "git add/rm ..." to update what will be committed)
> > (use "git checkout -- ..." to discard changes in working directory)
> > ```
> >     deleted:    content/en/project/template/bhs2020.png
> >     deleted:    content/en/project/template/dontpanic.jpg
> >     deleted:    content/en/project/template/enter.jpg
> >     deleted:    content/en/project/template/index.md
> > ```
> > 
> > 
> > Untracked files:
> > (use "git add ..." to include in what will be committed)
> > ```
> >     content/en/project/fMRI-sex-classification/bhs2020.png
> >     content/en/project/fMRI-sex-classification/dontpanic.jpg
> >     content/en/project/fMRI-sex-classification/enter.jpg
> > ```
> 
> Renaming considered as deleting. To commit these changes, I will have to use "git rm" which will again cause conflict.

And I could not find delete history of index.md

**Comment by tjays7** [comment]
> There are conflicts because you deleted the files inside the `project/template/` dir. Can you revert these changes? Once you push your changes on GH, it will automatically commit it to the pull request as well.
> 
> Thanks

I reverted all commits but still could not find the index.md deletion history. After messing up so much, I finally used git reset. Please let me know if its fine now.

**Comment by SamGuay** [comment]
Hi, I had to resolve conflicts locally, and then I had to make a new pull request. You can find you project page [here](https://school.brainhackmtl.org/project/fmri-sex-classification/). Feel free to make a new PR if you want to make any change :) Good job trying to solve it!

**Pull request closed without merging**
