### PR TITLE
Web site test

### PR DESCRIPTION
**Pull request by arsisabelle**

### CODE REVIEW

**Comment by pbellec** [comment]
LGTM. I think you forgot the first paragraph of the "background" from the template. You may want to remove that part before merging.

**Comment by arsisabelle** [comment]
Indeed! Thank you for letting me know! :) 

Oki, I just tried to commit push and then make a pull request for an updated version of the index.md (without BHS paragraph and with small text edits I caught while doing the revisions).

(I think it appears here as a 2nd commit)  Hopefully, this works now! (Fingers crossed!) 

Thank you for the patience and all the help and assistance! 

Isabelle

**Comment by pbellec** [comment]
LGTM, thanks for the submission!

**Comment by arsisabelle** [comment]
Youppi!! 🎆

**Comment by arsisabelle** [comment]
Hi again, @pbellec 

So sorry to bother you again!

I noticed today that only one image on my BHS website section was working and that the others did not display properly (I realized after searching a bit that it was because they were placed in different locations in my index.md than in my readme.md, which I had copy-pasted when trying to fix my submission problems). So that the website could correctly show all the pictures of my project, I corrected my index.md and images files and just made a push to /School.

Would you like me to make a new pull request? Or should I go to correct this?

Thank you and have an excellent day! I promise to not bother you more after lol!

Isabelle

**Comment by pbellec** [comment]
absolutely no worries.
Happy to merge other revisions if necessary.
Please open a new PR for these changes.

**Pull request merged**
